DROP TABLE IF EXISTS comments CASCADE;

--Создание таблицы комментариев
create TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    status VARCHAR(20) NOT NULL
);

--Индекс для поиска комментариев к событию
CREATE INDEX IF NOT EXISTS idx_comments_event_id ON comments(event_id);
--Индекс для поиска комментариев пользователя
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments(user_id);