DROP TABLE IF EXISTS users CASCADE;

--Создание таблицы пользователей
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

--Индекс для поиска пользователя по email
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);